- name: Bootstrap laptop
  import_playbook: playbooks/bootstrap.yml
  tags:
    - install
    - bootstrap

- name: Install software
  import_playbook: playbooks/install.yml
  tags:
    - install
    - update

- name: Configurations
  import_playbook: playbooks/configs.yml
  tags:
    - install
    - config