---
galaxy_info:
  author: Larry Smith Jr.
  description: Ansible role to install various Hashicorp Utils
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - precise
        - trusty
        - xenial
    - name: Debian
      versions:
        - jessie
        - stretch

  galaxy_tags:
    - development
dependencies: []
