---
- name: debian | Installing Pre-Reqs
  apt:
    name: ["unzip"]
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | installing HashiCorp Vagrant (x86_64)
  apt:
    deb: "{{ hashicorp_url }}/{{ item['name'] }}/{{ item['version'] }}/{{ item['name'] }}_{{ item['version'] }}_x86_64.deb"
    state: "{{ item['state'] }}"
  become: true
  loop: "{{ hashicorp_tools }}"
  when:
    - item['name'] == "vagrant"
    - not ansible_check_mode
