---
- name: install | Checking For Previously Installed Tools
  stat:
    path: "{{ hashicorp_install_dir }}/{{ item['name'] }}"
  register: _hashicorp_tools_installed
  loop: "{{ hashicorp_tools }}"

- name: install | Capturing Installed Versions of Tools # noqa 306
  shell: "{{ hashicorp_install_dir }}/{{ item['item']['name'] }} version | awk 'NR==1{ print substr($2,2) }'"
  register: _hashicorp_tools_installed_versions
  changed_when: false
  loop: "{{ _hashicorp_tools_installed['results'] }}"
  when: item['stat']['exists']

- name: install | Upgrading Existing Tools
  unarchive:
    src: "{{ hashicorp_url }}/{{ item['item']['item']['name'] }}/{{ item['item']['item']['version'] }}/{{ item['item']['item']['name'] }}_{{ item['item']['item']['version'] }}_{{ ansible_system|lower }}_amd64.zip" # noqa 204
    dest: "{{ hashicorp_install_dir }}"
    remote_src: true
  become: true
  loop: "{{ _hashicorp_tools_installed_versions['results'] }}"
  when:
    - item['item']['item']['name']|lower != "vagrant"
    - item['item']['item']['state']|lower == "present"
    - item['item']['stat']['exists']
    - item['stdout'] is defined
    - item['item']['item']['version'] != item['stdout']

- name: install | Installing Tools
  unarchive:
    src: "{{ hashicorp_url }}/{{ item['item']['item']['name'] }}/{{ item['item']['item']['version'] }}/{{ item['item']['item']['name'] }}_{{ item['item']['item']['version'] }}_{{ ansible_system|lower }}_amd64.zip" # noqa 204
    dest: "{{ hashicorp_install_dir }}"
    remote_src: true
  become: true
  loop: "{{ _hashicorp_tools_installed_versions['results'] }}"
  when:
    - item['item']['item']['name']|lower != "vagrant"
    - item['item']['item']['state']|lower == "present"
    - not item['item']['stat']['exists']
