---
- name: start snapd
  become: yes
  systemd:
    name: snapd
    state: started

- name: restart docker
  become: yes
  systemd:
    name: docker
    state: restarted

- name: reload udev
  become: yes
  shell: udevadm control --reload-rules && udevadm trigger
