---
- name: Start snapd
  become: true
  ansible.builtin.systemd:
    name: snapd
    state: started

- name: Restart docker
  become: true
  ansible.builtin.systemd:
    name: docker
    state: restarted

- name: Reload udev
  become: true
  ansible.builtin.shell: udevadm control --reload-rules && udevadm trigger
