---
- name: start snapd
  become: yes
  systemd:
    name: snapd
    state: started

- name: restart docker
  become: yes
  systemd:
    name: docker
    state: restarted

- name: restart udev
  become: yes
  systemd:
    name: udev
    state: restarted
