---
- name: Install Formula
  community.general.homebrew:
    name: "{{ brew_formulae }}"
    state: present
    path: "/home/{{ homebrew_user }}/.linuxbrew/bin"
  become_user: "{{ homebrew_user }}"
  become: yes
