---
- name: Test playbook
  user: ansible
  hosts: all
  gather_facts: yes
  become: true
  vars:
    homebrew_user: ansible
  pre_tasks:
    - debug:
        msg: "{{ ansible_os_family }}"
  roles:
    - ansible-homebrew