---
- name: Additions
  hosts: laptop
  become: false
  gather_facts: true
  tasks:

######### Fish shell addons and customization ############

    - name: Get fisher - create temp file
      ansible.builtin.tempfile:
        state: file
        suffix: fisher
      register: tempfile
      when: '"fish" in dnf_packages'

    - name: Get fisher - download script
      ansible.builtin.get_url:
        url: https://git.io/fisher
        dest: "{{ tempfile.path }}"
        mode: '0755'
      when: '"fish" in dnf_packages'

    - name: Get fisher - run script
      ansible.builtin.shell: source "{{ tempfile.path }}" && fisher install jorgebucaran/fisher
      args:
        executable: /usr/bin/fish
      changed_when: false
      when: '"fish" in dnf_packages'

    - name: Add fish-kubectl-completions
      ansible.builtin.shell: fisher install evanlucas/fish-kubectl-completions
      args:
        executable: /usr/bin/fish
      changed_when: false
      when:
        - '"fish" in dnf_packages'
        - '"kubectl" in snap_packages_classic'

    - name: Install addons
      ansible.builtin.shell: fisher install "{{ item }}"
      args:
        executable: /usr/bin/fish
      changed_when: false
      with_items: "{{ fisher_addons }}"
      when: '"fish" in dnf_packages'

    - name: Update addons
      ansible.builtin.shell: fisher update
      args:
        executable: /usr/bin/fish
      changed_when: false
      when: '"fish" in dnf_packages'

    - name: Copy Welcome screen
      ansible.builtin.copy:
        src: files/fish_greeting.fish
        dest: "/home/{{ ansible_user_id }}/.config/fish/functions/fish_greeting.fish"
        mode: "0600"
