---
- name: System tuning
  hosts: laptop
  become: yes
  gather_facts: yes
  handlers:
  - import_tasks: ../handlers/main.yml
  tasks:
  - name: Max User watches - sysctl
    lineinfile:
      path: /etc/sysctl.d/99-sysctl.conf
      regexp: 'fs.inotify.max_user_watches'
      line: 'fs.inotify.max_user_watches = 524288'

  - name: CLI history backward
    lineinfile:
      path: /etc/inputrc
      regexp: ' history-search-backward$'
      line: '"\e[A": history-search-backward'

  - name: CLI history forward
    lineinfile:
      path: /etc/inputrc
      regexp: ' history-search-forward'
      line: '"\e[B": history-search-forward'

  - name: Add mail server
    lineinfile:
      path: /etc/hosts
      regexp: 'mail.dt-one.com$'
      line: '10.239.107.6     mail.dt-one.com'

  - name: Create ~/.config/fish/conf.d/
    file:
      path: ~/.config/fish/conf.d/
      state: directory
      mode: 0755
      recurse: yes

  - name: Copy my fish config file
    template:
      src: templates/my.fish.j2
      dest: ~/.config/fish/conf.d/my.fish
      mode: 0600
    become: no

  - name: Copy my fish abbreviations file
    template:
      src: templates/abbr.fish.j2
      dest: ~/.config/fish/conf.d/abbr.fish
      mode: 0600
    become: no

  # - name: Copy update-systemd-resolved
  #   copy:
  #     src: files/update-systemd-resolved
  #     dest: /etc/openvpn/scripts/update-systemd-resolved
  #     mode: 0755

  - name: Copy gitconfig
    copy:
      src: files/gitconfig
      dest: ~/.gitconfig
      mode: 0600
    become: no

  # - name: Link to /run/systemd/resolve/stub-resolv.conf
  #   file:
  #     src: /run/systemd/resolve/stub-resolv.conf
  #     dest: /etc/resolv.conf
  #     state: link
  #     force: yes

  - name: Enable and start systemd-resolved
    systemd:
      name: systemd-resolved
      enabled: yes
      state: started

  - name: Docker custom config
    template:
      src: templates/docker_daemon.json.j2
      dest: /etc/docker/daemon.json
      mode: 0644
    notify: restart docker

  - name: Eanble and start docker
    systemd:
      name: docker
      enabled: yes
      state: started
    ### F32 is using cgroup v2. You may need  "GRUB_CMDLINE_LINUX= systemd.unified_cgroup_hierarchy=0" in /etc/default/grub + grub2-mkconfig

  - name: Create a volume portainer_data
    docker_volume:
      name: portainer_data

  - name: portainer
    docker_container:
      name: portainer
      image: portainer/portainer-ce:latest
      command: -H unix:///var/run/docker.sock
      container_default_behavior: compatibility
      pull: yes
      state: present
      privileged: yes
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data
      ports:
        - "9000:9000"
      env:
        TZ: "CET"

  - name: Xorg vs. Wayland
    lineinfile:
      path: /etc/gdm/custom.conf
      regexp: 'WaylandEnable='
      line: 'WaylandEnable={{ wayland }}'

  - ansible.posix.sysctl:
      name: fs.inotify.max_queued_events
      value: '524288'
      sysctl_file: /etc/sysctl.d/99-sysctl.conf
      reload: no

  - ansible.posix.sysctl:
      name: fs.inotify.max_user_instances
      value: '512'
      sysctl_file: /etc/sysctl.d/99-sysctl.conf
      reload: no

  - ansible.posix.sysctl:
      name: fs.inotify.max_user_watches
      value: '524288'
      sysctl_file: /etc/sysctl.d/99-sysctl.conf
      reload: no
