---
- name: System tuning
  hosts: laptop
  become: yes
  gather_facts: yes
  tasks:
  - name: CLI history backward
    lineinfile:
      path: /etc/inputrc
      regexp: ' history-search-backward$'
      line: '"\e[A": history-search-backward'

  - name: CLI history forward
    lineinfile:
      path: /etc/inputrc
      regexp: ' history-search-forward'
      line: '"\e[B": history-search-forward'

  - name: Add mail server
    lineinfile:
      path: /etc/hosts
      regexp: 'mail.dt-one.com$'
      line: '10.239.107.6     mail.dt-one.com'

  - name: Create ~/.config/fish/conf.d/
    file:
      path: ~/.config/fish/conf.d/
      state: directory
      mode: 0755
      recurse: yes

  - name: Copy my fish config file
    template:
      src: templates/my.fish.j2
      dest: ~/.config/fish/conf.d/my.fish
      mode: 0600
    become: no

  - name: Copy my fish abbreviations file
    template:
      src: files/abbr.fish
      dest: ~/.config/fish/conf.d/abbr.fish
      mode: 0600
    become: no

  - name: Copy openvpn-dt script file
    template:
      src: templates/openvpn-dt.j2
      dest: /usr/bin/openvpn-dt
      mode: 0755

  - name: Create /etc/openvpn/scripts/
    file:
      path: /etc/openvpn/scripts
      state: directory
      mode: 0755
      recurse: yes

  - name: Copy update-systemd-resolved
    copy:
      src: files/update-systemd-resolved
      dest: /etc/openvpn/scripts/update-systemd-resolved
      mode: 0755

  - name: Link to /run/systemd/resolve/stub-resolv.conf
    file:
      src: /run/systemd/resolve/stub-resolv.conf
      dest: /etc/resolv.conf
      state: link
      force: yes

  - name: Enable and start systemd-resolved
    systemd:
      name: systemd-resolved
      enabled: yes
      state: started

  - name: Eanble and start docker
    systemd:
      name: docker
      enabled: yes
      state: started
    ### F32 is using cgroup v2. You may need  "GRUB_CMDLINE_LINUX= systemd.unified_cgroup_hierarchy=0" in /etc/default/grub + grub2-mkconfig

  - name: Create a volume portainer_data
    docker_volume:
      name: portainer_data

  - name: portainer
    docker_container:
      name: portainer
      image: portainer/portainer-ce:latest
      command: -H unix:///var/run/docker.sock
      container_default_behavior: compatibility
      pull: yes
      state: started
      privileged: yes
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data
      ports:
        - "9000:9000"
      env:
        TZ: "CET"

  - name: Use Xorg instead of Wayland
    lineinfile:
      path: /etc/gdm/custom.conf
      regexp: 'WaylandEnable='
      line: 'WaylandEnable=false'