---
- name: Install Software
  hosts: laptop
  become: yes
  gather_facts: yes
  tasks:
  # - name: Update system
  #   import_role:
  #     name: robertdebock.update
  #   vars:
  #     update_reboot: no

  - name: Install pip
    import_role:
      name: geerlingguy.pip

  - name: Uninstall DNF Packages
    package:
      name: "{{ dnf_packages_absent }}"
      state: absent

  - name: Install DNF Packages
    package:
      name: "{{ dnf_packages }}"
      state: present

  - name: Install Snap Packages
    snap:
      name: "{{ snap_packages }}"

  - name: Install Snap Packages (Classic)
    snap:
      name: "{{ snap_packages_classic }}"
      classic: yes

  - name: Upgrade pip
    pip:
      name: pip
      extra_args: --upgrade

  - name: Install user pip packages
    pip:
      name: "{{ pip_packages }}"
      extra_args: --user --upgrade
    become: no

  - name: Install global pip packages
    pip:
      name: "{{ global_pip_packages }}"
      extra_args: --upgrade

  - name: Install and upgrade brew formulaes
    import_role:
      name: monolithprojects.homebrew

  - name: Install Kubeseal client
    import_role:
      name: andrewrothstein.kubeseal

  - name: Install k3d
    import_role:
      name: andrewrothstein.k3d

  - name: Install k9s
    import_role:
      name: andrewrothstein.k9s

  # - name: Install asdf
  #   import_role:
  #     name: cimon-io.asdf
  #   vars:
  #     asdf_plugins: []

  # - name: Set up aws-cli2
  #   import_role:
  #     name: dzangolab.awscli2
