---
- name: Install Software
  hosts: laptop
  become: true
  gather_facts: true
  tasks:

    - name: Install pip
      ansible.builtin.import_role:
        name: geerlingguy.pip

    - name: Install Docker
      ansible.builtin.import_role:
        name: geerlingguy.docker

    - name: Uninstall DNF Packages
      ansible.builtin.package:
        name: "{{ dnf_packages_absent }}"
        state: absent

    - name: Install DNF Packages
      ansible.builtin.package:
        name: "{{ dnf_packages }}"
        state: present

    - name: Install Snap Packages
      community.general.packaging.os.snap:
        name: "{{ snap_packages }}"

    - name: Install Snap Packages (Classic)
      community.general.packaging.os.snap:
        name: "{{ snap_packages_classic }}"
        classic: true

    - name: Upgrade pip
      ansible.builtin.pip:
        name: pip
        extra_args: --upgrade

    - name: Install user pip packages
      ansible.builtin.pip:
        name: "{{ pip_packages }}"
        extra_args: --user --upgrade
      become: false

    - name: Install global pip packages
      ansible.builtin.pip:
        name: "{{ global_pip_packages }}"
        extra_args: --upgrade

    - name: Install and upgrade brew formulaes
      ansible.builtin.import_role:
        name: monolithprojects.homebrew

    - name: Install k9s
      ansible.builtin.import_role:
        name: andrewrothstein.k9s

    - name: ArgoCD CLI
      ansible.builtin.import_role:
        name: andrewrothstein.argocd
