name: Ansible check

on: [push, pull_request]

jobs:
    ansible_check:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-18.04]
        steps:
        - uses: actions/checkout@master
        - name: Ansible check
          run: |
            ansible-playbook --connection=local -i .github/hosts.ini -e 'ansible_python_interpreter=/usr/bin/python3' site.yml --check